### ISSUE TITLE
[Sprint 2 - US#2] Add UI Option for Selecting Specific Users

### ISSUE THREAD

**Issue by Alanna-Cao** [CMU-313/nodebb-f24-team-sweepers#18]
### Create a UI option (dropdown or checkbox) that allows students to select specific users (TAs, instructors) to view their post.

The estimated effort to complete this issue is **Low-Medium (4 hours)**. 

There are **no dependencies** for this issue.

**Acceptance Criteria:**
- A functional dropdown or checkbox list is available in the post creation UI
- Dropdown allows students to select specific users (TAs, instructors, both) who can view their post
- Test by confirming the dropdown appears in the post creation UI

**Milestone**: Sprint 2

**Comment by sofian-syed** [comment]
This issue was completed and merged into sprint 2 main branches
